### ISSUE TITLE
Spawn Digimon Number: 1 with image.

### ISSUE THREAD

**Issue by I-question-this** [I-question-this/redbot-digicord-cog#7]
- [x] Folder path for images should be within the save location for Redbot cogs (Images should be not be hard coded into this repository). This was completed in #10
- [x] Since #10 was completed, use the actual image
- [x] Since #9 was completed, use the Digimon class. Create a "random" digimon function or modify the spawn function.
